// apps/web/src/components/PageHeader.tsx
import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import './PageHeader.css';

export interface PageHeaderProps {
  /** Editorial index number, e.g. "02". */
  index: string;
  /** Short uppercase mono label, e.g. "GRAPH". */
  kicker: string;
  /** Page title. */
  title: string;
  /** Optional plain-text description. */
  description?: string;
  /** Optional back target; renders a declarative back link when set. */
  backTo?: string;
  /** Right-aligned actions slot. */
  actions?: ReactNode;
}

export function PageHeader({ index, kicker, title, description, backTo, actions }: PageHeaderProps) {
  return (
    <header className="page-header">
      <div className="page-header__meta">
        <span className="page-header__folio">
          <span className="page-header__index">{index}</span>
          <span className="page-header__sep" aria-hidden="true">·</span>
          <span className="page-header__kicker">{kicker}</span>
        </span>
        {backTo && (
          <Link to={backTo} className="page-header__back">
            ← 返回
          </Link>
        )}
      </div>

      <div className="page-header__bar">
        <h1 className="page-header__title">{title}</h1>
        {actions && <div className="page-header__actions">{actions}</div>}
      </div>

      {description && <p className="page-header__desc">{description}</p>}
    </header>
  );
}

// apps/web/src/components/PageHeader.vue
<template>
  <header class="page-header">
    <div class="page-header__meta">
      <span class="page-header__folio">
        <span class="page-header__index">{{ index }}</span>
        <span class="page-header__sep" aria-hidden="true">·</span>
        <span class="page-header__kicker">{{ kicker }}</span>
      </span>
      <router-link v-if="backTo" :to="backTo" class="page-header__back">← 返回</router-link>
    </div>

    <div class="page-header__bar">
      <h1 class="page-header__title">{{ title }}</h1>
      <div v-if="$slots.actions" class="page-header__actions">
        <slot name="actions" />
      </div>
    </div>

    <p v-if="description" class="page-header__desc">{{ description }}</p>
  </header>
</template>

<script setup lang="ts">
import type { RouteLocationRaw } from 'vue-router';

defineProps<{
  /** Editorial index number, e.g. "02". */
  index: string;
  /** Short uppercase mono label, e.g. "GRAPH". */
  kicker: string;
  /** Page title. */
  title: string;
  /** Optional plain-text description. */
  description?: string;
  /** Optional back target; renders a declarative back link when set. */
  backTo?: RouteLocationRaw;
}>();
</script>

<style scoped>
.page-header {
  min-width: 0;
  padding-bottom: var(--qg-space-4);
  border-bottom: 1px solid var(--qg-line);
}

/* Meta row: editorial folio (index · kicker) + optional back link. */
.page-header__meta {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: var(--qg-space-2);
  min-width: 0;
  margin-bottom: var(--qg-space-3);
}

.page-header__folio {
  display: inline-flex;
  align-items: baseline;
  gap: var(--qg-space-1);
  min-width: 0;
}

.page-header__index,
.page-header__sep,
.page-header__kicker {
  font-family: var(--qg-font-mono);
  font-size: 11px;
  line-height: 1;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--qg-faint);
}

.page-header__back {
  margin-left: auto;
  font-family: var(--qg-font-mono);
  font-size: 11px;
  letter-spacing: 0.04em;
  color: var(--qg-muted);
  text-decoration: none;
  transition: color var(--qg-duration) ease;
}

.page-header__back:hover {
  color: var(--qg-fg);
}

/* Title row: title + right-aligned actions. */
.page-header__bar {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: var(--qg-space-4);
  min-width: 0;
}

.page-header__title {
  min-width: 0;
  margin: 0;
  font-family: var(--qg-font-display);
  font-size: 24px;
  font-weight: 600;
  line-height: 1.15;
  color: var(--qg-fg);
}

.page-header__actions {
  display: flex;
  align-items: center;
  gap: var(--qg-space-2);
  min-width: 0;
}

.page-header__desc {
  margin: var(--qg-space-2) 0 0;
  color: var(--qg-muted);
  font-size: 13px;
  line-height: 1.6;
}

/* Stack title above actions on narrow viewports. */
@media (max-width: 900px) {
  .page-header__bar {
    flex-direction: column;
    align-items: stretch;
    gap: var(--qg-space-2);
  }
}

/* Let actions wrap without ever overlapping the title. */
@media (max-width: 768px) {
  .page-header__actions {
    display: flex;
    flex-wrap: wrap;
    gap: var(--qg-space-2);
    min-width: 0;
  }
}
</style>
