// apps/web/src/views/IndexManager.tsx
import { useEffect, useRef, useState } from 'react';
import http from '@/lib/http';
import { PageHeader } from '@/components/PageHeader';
import { ElButton, ElCard, ElDescriptions, ElProgress, ElTag } from '@/components/el';
import { useCurrentRepo } from '@/hooks/useCurrentRepo';
import './IndexManager.css';

interface IndexStatus {
  status?: string;
  repoName?: string;
  totalFiles?: number;
  totalNodes?: number;
  totalEdges?: number;
  lastBuildTime?: string;
  phase?: string;
  message?: string;
  progress?: number;
  error?: string;
}

function statusTagType(s?: string) {
  if (s === 'ready') return 'success' as const;
  if (s === 'building') return 'warning' as const;
  if (s === 'error') return 'danger' as const;
  return 'info' as const;
}

export default function IndexManager() {
  const { currentRepo } = useCurrentRepo();

  const [status, setStatus] = useState<IndexStatus>({});
  const [building, setBuilding] = useState(false);
  const [progress, setProgress] = useState(0);
  // WebSocket 回调里要基于最新 status 合并，用 ref 兜住闭包。
  const statusRef = useRef<IndexStatus>({});
  statusRef.current = status;

  async function refreshStatus() {
    try {
      const res = await http.get('/api/index/status');
      const next = res.data as IndexStatus;
      setStatus(next);
      if (next.status === 'building') {
        setBuilding(true);
        setProgress(Number(next.progress) || 0);
      } else {
        setBuilding(false);
        if (typeof next.progress === 'number') {
          setProgress(next.progress);
        }
      }
    } catch {
      // ignore
    }
  }

  // 切换仓库后刷新索引状态
  useEffect(() => {
    void refreshStatus();
  }, [currentRepo]);

  useEffect(() => {
    const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
    const socket = new WebSocket(`${protocol}://${window.location.host}/ws/progress`);

    socket.onmessage = (event) => {
      try {
        const payload = JSON.parse(event.data);
        if (payload.type !== 'index-progress') return;
        setStatus({
          ...statusRef.current,
          status: payload.status,
          repoName: payload.repoName ?? statusRef.current.repoName,
          progress: payload.progress,
          phase: payload.phase,
          message: payload.message,
          error: payload.error,
        });
        setProgress(Number(payload.progress) || 0);
        setBuilding(payload.status === 'building');
        if (payload.status === 'ready' || payload.status === 'error') {
          void refreshStatus();
        }
      } catch {
        // ignore invalid message
      }
    };

    return () => socket.close();
  }, []);

  async function triggerBuild() {
    try {
      const res = await http.post('/api/index/build');
      if (res.data?.status === 'building') {
        setBuilding(true);
        setProgress(0);
        setStatus((prev) => ({
          ...prev,
          status: 'building',
          message: res.data.message,
          repoName: res.data.repoName,
        }));
      }
      await refreshStatus();
    } catch {
      // ignore
    }
  }

  async function triggerRebuild() {
    try {
      const res = await http.post('/api/index/rebuild');
      if (res.data?.status === 'building') {
        setBuilding(true);
        setProgress(0);
        setStatus((prev) => ({
          ...prev,
          status: 'building',
          message: res.data.message,
          repoName: res.data.repoName,
        }));
      }
      await refreshStatus();
    } catch {
      // ignore
    }
  }

  return (
    <div className="index-manager">
      <PageHeader index="03" kicker="INDEX" title="索引管理" backTo="/" />

      <ElCard className="status-card" header="索引状态">
        <ElDescriptions
          column={2}
          border
          items={[
            { label: '状态', content: <ElTag type={statusTagType(status.status)}>{status.status}</ElTag> },
            { label: '仓库', content: status.repoName || '--' },
            { label: '文件数', content: status.totalFiles || '--' },
            { label: '节点数', content: status.totalNodes || '--' },
            { label: '边数', content: status.totalEdges || '--' },
            { label: '最近构建', content: status.lastBuildTime || '--' },
            { label: '阶段', content: status.phase || '--' },
            { label: '信息', content: status.message || '--' },
          ]}
        />
      </ElCard>

      <div className="actions">
        <ElButton type="primary" onClick={triggerBuild} loading={building}>
          全量构建
        </ElButton>
        <ElButton onClick={triggerRebuild} loading={building}>
          增量重建
        </ElButton>
      </div>

      {building && (
        <ElCard className="progress-card" header="构建进度">
          <ElProgress percentage={progress} status={progress === 100 ? 'success' : undefined} />
          <p className="progress-text">{status.message || '处理中...'}</p>
        </ElCard>
      )}
    </div>
  );
}

// apps/web/src/views/IndexManager.vue
<template>
  <div class="index-manager">
    <PageHeader index="03" kicker="INDEX" title="索引管理" :back-to="{ name: 'Home' }" />

    <el-card class="status-card">
      <template #header>索引状态</template>
      <el-descriptions :column="2" border>
        <el-descriptions-item label="状态">
          <el-tag :type="statusTag">{{ status.status }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="仓库">{{ status.repoName || '--' }}</el-descriptions-item>
        <el-descriptions-item label="文件数">{{ status.totalFiles || '--' }}</el-descriptions-item>
        <el-descriptions-item label="节点数">{{ status.totalNodes || '--' }}</el-descriptions-item>
        <el-descriptions-item label="边数">{{ status.totalEdges || '--' }}</el-descriptions-item>
        <el-descriptions-item label="最近构建">{{ status.lastBuildTime || '--' }}</el-descriptions-item>
        <el-descriptions-item label="阶段">{{ status.phase || '--' }}</el-descriptions-item>
        <el-descriptions-item label="信息">{{ status.message || '--' }}</el-descriptions-item>
      </el-descriptions>
    </el-card>

    <div class="actions">
      <el-button type="primary" @click="triggerBuild" :loading="building">全量构建</el-button>
      <el-button @click="triggerRebuild" :loading="building">增量重建</el-button>
    </div>

    <el-card v-if="building" class="progress-card">
      <template #header>构建进度</template>
      <el-progress :percentage="progress" :status="progress === 100 ? 'success' : undefined" />
      <p class="progress-text">{{ status.message || '处理中...' }}</p>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue';
import http from '@/lib/http';
import PageHeader from '@/components/PageHeader.vue';
import { useCurrentRepo } from '@/composables/useCurrentRepo';

const { currentRepo } = useCurrentRepo();

const status = ref<any>({});
const building = ref(false);
const progress = ref(0);
const ws = ref<WebSocket | null>(null);

const statusTag = computed(() => {
  const s = status.value.status;
  if (s === 'ready') return 'success';
  if (s === 'building') return 'warning';
  if (s === 'error') return 'danger';
  return 'info';
});

async function refreshStatus() {
  try {
    const res = await http.get('/api/index/status');
    status.value = res.data;
    if (status.value.status === 'building') {
      building.value = true;
      progress.value = Number(status.value.progress) || 0;
    } else {
      building.value = false;
      if (typeof status.value.progress === 'number') {
        progress.value = status.value.progress;
      }
    }
  } catch {
    // ignore
  }
}

function connectProgressWs() {
  const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
  const wsUrl = `${protocol}://${window.location.host}/ws/progress`;
  const socket = new WebSocket(wsUrl);
  ws.value = socket;

  socket.onmessage = (event) => {
    try {
      const payload = JSON.parse(event.data);
      if (payload.type !== 'index-progress') return;
      status.value = {
        ...status.value,
        status: payload.status,
        repoName: payload.repoName ?? status.value.repoName,
        progress: payload.progress,
        phase: payload.phase,
        message: payload.message,
        error: payload.error,
      };
      progress.value = Number(payload.progress) || 0;
      building.value = payload.status === 'building';
      if (payload.status === 'ready' || payload.status === 'error') {
        void refreshStatus();
      }
    } catch {
      // ignore invalid message
    }
  };
}

// 切换仓库后刷新索引状态
watch(currentRepo, () => {
  refreshStatus();
});

onMounted(async () => {
  await refreshStatus();
  connectProgressWs();
});

onBeforeUnmount(() => {
  if (ws.value) {
    ws.value.close();
    ws.value = null;
  }
});

async function triggerBuild() {
  try {
    const res = await http.post('/api/index/build');
    if (res.data?.status === 'building') {
      building.value = true;
      progress.value = 0;
      status.value = { ...status.value, status: 'building', message: res.data.message, repoName: res.data.repoName };
    }
    await refreshStatus();
  } catch {
    // ignore
  }
}

async function triggerRebuild() {
  try {
    const res = await http.post('/api/index/rebuild');
    if (res.data?.status === 'building') {
      building.value = true;
      progress.value = 0;
      status.value = { ...status.value, status: 'building', message: res.data.message, repoName: res.data.repoName };
    }
    await refreshStatus();
  } catch {
    // ignore
  }
}
</script>

<style scoped>
.index-manager {
  max-width: 900px;
  margin: 0 auto;
  padding: 24px 20px;
}

.status-card {
  margin: 20px 0;
}

.actions {
  margin-bottom: 20px;
}

.progress-card {
  margin-bottom: 20px;
}

.progress-text {
  margin-top: 12px;
  color: #606266;
  font-size: 13px;
}
</style>
